### ISSUE TITLE
Ability to specify init-hook

### ISSUE THREAD

**Issue by madvas** [thusoy/grunt-pylint#11]
It would be nice if one could specify `init-hook` as string of python commands in grunt-pylint options.
There reason why I can't put it in pylintrc is because it needs to be computed at run time

Thanks a lot, good job with the module! :)

**Comment by thusoy** [comment]
That should be possible, I'll see what I can do. I'm just curious though, what do you need it for?

**Comment by madvas** [comment]
Thank you! The reason is simple: 
If you want to use Google App Engine Python SDK, you have to save it manually somewhere in your computer (anyone can save it in different location). Pylint then complains about app engine imports and method calls unless you include manually path to your google sdk in your .pylintrc 
`init-hook=import sys; sys.path.append("/path/to/your/googlesdk");`

Then it's all ok. 
But if you want to distribute code that works "out of the box", it's unpleasant extra step to always manually set this path.
So I would programatically locate google sdk (by locating dev_appserver command) and then pass this path to grunt in init-hook option. 

Of course one could just disable all these errors related to app engine sdk, but that's not the best solution :)

**Comment by thusoy** [comment]
I added an initHook option in v1.2.0 which is pushed to npm now, let me know if there's any issues!

**Comment by madvas** [comment]
Looks great, thank you very much!
