### ISSUE TITLE
Cannot install grunt-pylint

### ISSUE THREAD

**Issue by AtulUjjwal** [thusoy/grunt-pylint#13]
Getting this error everytime i try to install:
 $ npm install grunt-pylint
npm WARN package.json main@0.0.1 No repository field.
npm WARN package.json main@0.0.1 No license field.

> grunt-pylint@1.2.0 postinstall C:\users\kyagnik\gfeclient\node_modules\grunt-pylint
> cd tasks/lib && pip install --no-index --no-deps ./pylint-1.4.1.tar.gz ./astroid-1.3.4.tar.gz ./colorama-0.3.3.tar.gz ./logilab-common-0.63.2.tar.gz ./six-1.9.0.tar.gz --target .

'pip' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt-pylint"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! grunt-pylint@1.2.0 postinstall: `cd tasks/lib && pip install --no-index --no-deps ./pylint-1.4.1.tar.gz ./astroid-1.3.4.tar.gz ./colorama-0.3.3.tar.gz ./logilab-common-0.63.2.tar.gz ./six-1.9.0.tar.gz --target .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grunt-pylint@1.2.0 postinstall script 'cd tasks/lib && pip install --no-index --no-deps ./pylint-1.4.1.tar.gz ./astroid-1.3.4.tar.gz ./colorama-0.3.3.tar.gz ./logilab-common-0.63.2.tar.gz ./six-1.9.0.tar.gz --target .'.
npm ERR! This is most likely a problem with the grunt-pylint package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd tasks/lib && pip install --no-index --no-deps ./pylint-1.4.1.tar.gz ./astroid-1.3.4.tar.gz ./colorama-0.3.3.tar.gz ./logilab-common-0.63.2.tar.gz ./six-1.9.0.tar.gz --target .
npm ERR! You can get their info via:
npm ERR!     npm owner ls grunt-pylint
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by thusoy** [comment]
It seems you do not have `pip` in your `PATH`, which is required for `grunt-pylint` to install (as noted in the readme). Make sure you [install pip](https://pip.pypa.io/en/stable/installing/) first and then try again, let me know if it still fails for you.

**Comment by kunalyagnik** [comment]
Hi I too tried to install the same i installed pip using npm install pip. It gets installed and i can see the folder inside node_modules as well.
But when we try to install $npm install grunt-pylint --save-dev I get exception from node_modules\pip\lib\cli.js it throws exception object expected

![image](https://cloud.githubusercontent.com/assets/16697565/12316383/e1c714ae-baab-11e5-9050-b4073ac69b25.png)
However I can still see the git pylint folder copied inside node module.
Also when I try to register a task and runt $grunt task it runs ssuccessfully but does nothing

**Comment by thusoy** [comment]
That's the wrong pip, you have to follow the link I gave in the previous post to install the correct one, it's a python module and not available through npm.

**Comment by kunalyagnik** [comment]
Thanks a ton...

**Comment by thusoy** [comment]
Anytime, happy to help. I'll clarify in the readme that it's the python pip that is required.
