### ISSUE TITLE
Ability to specify a single test

### ISSUE THREAD

**Issue by nadavoosh** [thusoy/grunt-pylint#18]
I love using grunt-pylint as my python linter. However -- how can I grep for a single test?

**Comment by thusoy** [comment]
Glad you like it. Not sure if I understand what you're asking, but all tests pylint runs against your code can be found [here](https://docs.pylint.org/features.html), these can be enabled/disabled individually by using the `enable` or `disable` options to `grunt-pylint`. Does that answer your question?

**Comment by nadavoosh** [comment]
Thanks, maybe I can rephrase. I currently run all my tests with `grunt test`. I would like to be able to run a single test with `grunt test --grep 'some single test'`. Is that something simple? Thanks again.

**Comment by thusoy** [comment]
grunt-pylint doesn't have anything to do with running tests, you'll have to check that with the plugin that runs your tests. I can only answer for grunt-nose, another project of mine, where we don't do any parsing of command line arguments, but you might be able to specify the test to run in the gruntfile.

**Comment by nadavoosh** [comment]
Oops -- yea, I should have posted this in grunt-nose. Thanks for clarifying, anyway.
